# fly.toml app configuration file generated for diagram-hub on 2023-04-29T17:05:52-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "diagram-hub"
primary_region = "iad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
